<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RaceInfo extends \App\Entities\RaceInfo implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'babaState' => [parent::class, 'babaState', null],
        "\0".parent::class."\0".'courseType' => [parent::class, 'courseType', null],
        "\0".parent::class."\0".'distance' => [parent::class, 'distance', null],
        "\0".parent::class."\0".'entryHorceCount' => [parent::class, 'entryHorceCount', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'jyoCd' => [parent::class, 'jyoCd', null],
        "\0".parent::class."\0".'raceDate' => [parent::class, 'raceDate', null],
        "\0".parent::class."\0".'raceName' => [parent::class, 'raceName', null],
        "\0".parent::class."\0".'raceNum' => [parent::class, 'raceNum', null],
        "\0".parent::class."\0".'rotation' => [parent::class, 'rotation', null],
        "\0".parent::class."\0".'weather' => [parent::class, 'weather', null],
        'babaState' => [parent::class, 'babaState', null],
        'courseType' => [parent::class, 'courseType', null],
        'distance' => [parent::class, 'distance', null],
        'entryHorceCount' => [parent::class, 'entryHorceCount', null],
        'id' => [parent::class, 'id', null],
        'jyoCd' => [parent::class, 'jyoCd', null],
        'raceDate' => [parent::class, 'raceDate', null],
        'raceName' => [parent::class, 'raceName', null],
        'raceNum' => [parent::class, 'raceNum', null],
        'rotation' => [parent::class, 'rotation', null],
        'weather' => [parent::class, 'weather', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
