<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormationVotingRecord extends \App\Entities\FormationVotingRecord implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'howToBuyMst' => [parent::class, 'howToBuyMst', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'raceInfo' => [parent::class, 'raceInfo', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'votingAmountFormation' => [parent::class, 'votingAmountFormation', null],
        "\0".parent::class."\0".'votingUmaBan1' => [parent::class, 'votingUmaBan1', null],
        "\0".parent::class."\0".'votingUmaBan2' => [parent::class, 'votingUmaBan2', null],
        "\0".parent::class."\0".'votingUmaBan3' => [parent::class, 'votingUmaBan3', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'howToBuyMst' => [parent::class, 'howToBuyMst', null],
        'id' => [parent::class, 'id', null],
        'raceInfo' => [parent::class, 'raceInfo', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'user' => [parent::class, 'user', null],
        'votingAmountFormation' => [parent::class, 'votingAmountFormation', null],
        'votingUmaBan1' => [parent::class, 'votingUmaBan1', null],
        'votingUmaBan2' => [parent::class, 'votingUmaBan2', null],
        'votingUmaBan3' => [parent::class, 'votingUmaBan3', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
