version: '3.8'

services:
  # PHP-FPM (Laravel) サービス
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./keiba-simulation-app:/var/www
    networks:
      - laravel
    command: sh -c "php artisan migrate --force && php-fpm"

  # Nginx サービス
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./keiba-simulation-app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

